d8_progress_entity.progress_entity_type.*:
  type: config_entity
  label: 'Progress entity type config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
